name: Executar Testes Cucumber

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Fazer checkout do código do repositório
        uses: actions/checkout@v4

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Instalar dependências do projeto
        run: bundle install

      - name: Instalar dependências do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Instalar dependências do Node.js
        run: npm install

      - name: Iniciar o servidor
        run: Start-Process -FilePath "npm" -ArgumentList "run serve" -NoNewWindow
        env:
          CI: true

      - name: Aguardar o servidor estar pronto
        run: npx wait-on http://localhost:8080 --timeout 300000 

      - name: Verificar se o servidor está em execução
        run: curl -I http://localhost:8080

      - name: Executar testes Cucumber
        run: bundle exec cucumber

      - name: Parar o servidor
        run: taskkill /F /IM node.exe